/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Address type classification information
 */
export interface AddressTypeDto {
  /**
   * Unique address type identifier - primary key
   */
  addressTypeId: number;
  /**
   * Address type description/designation
   */
  addressDescription?: string;
  /**
   * Table text
   */
  tableText?: string;
  /**
   * AP flag
   */
  apFlag?: string;
  /**
   * Partner flag
   */
  partnerFlag?: string;
  /**
   * Last modification date
   */
  modificationDate?: string;
}

