/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Communication type classification information
 */
export interface CommunicationTypeDto {
  /**
   * Unique communication type identifier - primary key
   */
  communicationTypeId: number;
  /**
   * Communication type description/designation
   */
  communicationDescription?: string;
  /**
   * Table text - required field
   */
  tableText: string;
  /**
   * AP flag
   */
  apFlag?: string;
  /**
   * Partner flag
   */
  partnerFlag?: string;
  /**
   * Last modification date
   */
  modificationDate?: string;
}

