/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group member information from CF_GET_GROUP_MEMBERS view
 */
export interface GroupMembersDto {
  /**
   * Group number this member belongs to
   */
  groupNumber?: number;
  /**
   * Partner number of the group member
   */
  partnerNumber?: number;
  /**
   * Alpha code of the group member
   */
  alphaCode?: string;
  /**
   * First name part
   */
  name1?: string;
  /**
   * Second name part
   */
  name2?: string;
  /**
   * Third name part
   */
  name3?: string;
  /**
   * Type of the group member
   */
  type?: string;
}

