/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {GroupMembersSearchCriteriaSummary} from './group-members-search-criteria-summary';
import {GroupMembersDto} from './group-members-dto';


/**
 * Group members search response with results and metadata
 */
export interface GroupMembersResponse {
  /**
   * List of group members
   */
  members: Array<GroupMembersDto>;
  /**
   * Total number of group members
   */
  totalCount?: number;
  /**
   * Number of members returned in this response
   */
  returnedCount?: number;
  searchCriteria?: GroupMembersSearchCriteriaSummary;
}

