/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BankConnectionDto} from './bank-connection-dto';
import {GroupAssignmentDto} from './group-assignment-dto';
import {ContactPersonDto} from './contact-person-dto';


/**
 * Partner information containing comprehensive business details and related entities
 */
export interface PartnerDto {
  /**
   * Unique partner identifier - primary key. Optional for new partners (auto-generated), required for updates.
   */
  partnerNumber?: number;
  /**
   * Company group identifier
   */
  companyGroupId?: number;
  /**
   * Business group identifier
   */
  businessGroupId?: number;
  /**
   * Credit business flag
   */
  creditFlag?: boolean;
  /**
   * Leasing business flag
   */
  leasingFlag?: boolean;
  /**
   * Factoring business flag
   */
  factoringFlag?: boolean;
  /**
   * Main industry classification code
   */
  mainIndustry?: number;
  /**
   * Sub-industry classification code
   */
  subIndustry?: number;
  /**
   * Primary credit rating
   */
  creditRating1?: string;
  /**
   * Secondary credit rating
   */
  creditRating2?: string;
  /**
   * Legal form code
   */
  legalForm?: number;
  /**
   * Date when partner became customer
   */
  customerSince?: string;
  /**
   * Current partner status
   */
  partnerStatus?: string;
  /**
   * Area postal code
   */
  areaPostalCode?: string;
  /**
   * Group/Concern identifier
   */
  groupId?: number;
  /**
   * Assigned advisor/supervisor ID
   */
  advisor?: string;
  /**
   * ID of person who made last modification
   */
  modifierId?: string;
  /**
   * Last modification date
   */
  modificationDate?: string;
  /**
   * Number of master accounts
   */
  masterAccounts?: number;
  /**
   * Branch number
   */
  branchNumber?: number;
  /**
   * Sync host flag
   */
  syncHost?: string;
  /**
   * Commercial business flag
   */
  commercialFlag?: boolean;
  /**
   * Recording flag
   */
  recordingFlag?: boolean;
  /**
   * Deletion flag
   */
  deletionFlag?: boolean;
  /**
   * Deletion date
   */
  deletionDate?: string;
  /**
   * Secondary branch number
   */
  branchNumber2?: number;
  /**
   * Organization form
   */
  organizationForm?: string;
  /**
   * BM documents count
   */
  bmDocuments?: number;
  /**
   * BBK number
   */
  bbkNumber?: number;
  /**
   * SCHUFA flag
   */
  schufaFlag?: boolean;
  /**
   * Balance sheet date
   */
  balanceSheetDate?: string;
  /**
   * Basel flag
   */
  baselFlag?: boolean;
  /**
   * Insolvency flag
   */
  insolvencyFlag?: boolean;
  /**
   * SPM number
   */
  spmNumber?: string;
  /**
   * Freelancer flag
   */
  freelancerFlag?: boolean;
  /**
   * Insolvency status code
   */
  insolvencyStatus?: number;
  /**
   * Insolvency comment/remark
   */
  insolvencyComment?: string;
  /**
   * SG rating
   */
  sgRating?: string;
  /**
   * Probability of Default (PD)
   */
  probabilityOfDefault?: number;
  /**
   * Rating version
   */
  ratingVersion?: string;
  /**
   * Rating valid from date
   */
  ratingFrom?: string;
  /**
   * Rating valid to date
   */
  ratingTo?: string;
  /**
   * Rating user ID
   */
  ratingUser?: string;
  /**
   * Craftsman flag
   */
  craftsmanFlag?: boolean;
  /**
   * Non-profit organization flag
   */
  nonProfitFlag?: boolean;
  /**
   * Private participation flag
   */
  privateParticipationFlag?: boolean;
  /**
   * Balance sheet total amount
   */
  balanceSheetTotal?: number;
  /**
   * Rating reason/justification
   */
  ratingReason?: string;
  /**
   * Risk flag (default: true)
   */
  riskFlag?: boolean;
  /**
   * SG rating date
   */
  sgRatingDate?: string;
  /**
   * SG rating valid to date
   */
  sgRatingTo?: string;
  /**
   * KNE BBK number
   */
  kneBbkNumber?: number;
  /**
   * List of contact persons associated with this partner
   */
  contactPersons?: Array<ContactPersonDto>;
  /**
   * List of group assignments for this partner including assignment details
   */
  groupAssignments?: Array<GroupAssignmentDto>;
  /**
   * List of bank connections for this partner including detailed banking information
   */
  bankConnections?: Array<BankConnectionDto>;
}

