/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of search criteria used for this group search
 */
export interface PartnerGroupSearchCriteriaSummary {
  /**
   * Partner number searched for
   */
  partnerNumber?: number;
  /**
   * Alpha code searched for
   */
  alphaCode?: string;
  /**
   * Name searched for
   */
  name?: string;
  /**
   * First name searched for
   */
  firstname?: string;
  /**
   * Birthday searched for
   */
  birthday?: string;
  /**
   * postcode searched for
   */
  postCode?: string;
  /**
   * city searched for
   */
  city?: string;
  /**
   * street address searched for
   */
  street?: string;
}

