/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PartnerGroupSearchDto} from './partner-group-search-dto';
import {PartnerGroupSearchCriteriaSummary} from './partner-group-search-criteria-summary';


/**
 * Partner group search response with results and metadata
 */
export interface PartnerGroupSearchResponse {
  /**
   * List of partner group search results
   */
  partners: Array<PartnerGroupSearchDto>;
  /**
   * Total number of matching partners
   */
  totalCount?: number;
  /**
   * Number of partners returned in this response
   */
  returnedCount?: number;
  searchCriteria?: PartnerGroupSearchCriteriaSummary;
}

