/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchDto } from './branch-dto';
import { SalesAreaFocusDto } from './sales-area-focus-dto';


/**
 * Sales area data response containing branch offices and sales area focus information
 */
export interface SalesAreaDataResponse { 
    /**
     * List of all branch offices ordered by designation
     */
    branches: Array<BranchDto>;
    /**
     * List of active sales area focus entries ordered by branch and area name
     */
    salesAreaFocus: Array<SalesAreaFocusDto>;
}

