/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sales area focus information containing advisor assignments and regional data
 */
export interface SalesAreaFocusDto {
  /**
   * Unique area identifier - primary key
   */
  areaNumber: number;
  /**
   * Deletion flag (0 = active, others = deleted)
   */
  deletionFlag?: number;
  /**
   * Region number
   */
  regionNumber?: number;
  /**
   * Branch number
   */
  branchNumber?: number;
  /**
   * Team number
   */
  teamNumber?: number;
  /**
   * Focus indicator
   */
  focus?: string;
  /**
   * Advisor number
   */
  advisorNumber?: string;
  /**
   * Area name
   */
  areaName?: string;
  /**
   * User ID
   */
  userId?: string;
  /**
   * Sort order
   */
  sortOrder?: number;
  /**
   * Type indicator
   */
  type?: string;
  /**
   * Last modification date
   */
  lastModified?: string;
}

