spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-partner-edit}:5432/app-partner-edit-db
spring.datasource.username=partner_search_ro
spring.datasource.password=partner_search_ro
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.flyway.enabled=false
# Server Configuration
server.port=8445
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
server.http2.enabled=true
server.ssl.client-auth=none
partner.search.max-results=200
partner.complete.max-results=15
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.com.example.partner=DEBUG
spring.elasticsearch.uris=http://elasticsearch-partner-search:9200
