quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:postgres-lab}:5432/${DB_NAME:app-lab-db}

quarkus.hibernate-orm.schema-management.strategy=none

# No TLS — lab-only service
quarkus.http.insecure-requests=enabled
quarkus.http.port=${QUARKUS_HTTP_PORT:8080}

quarkus.elasticsearch.hosts=${ES_HOST:elasticsearch-lab-bulk}:9200
quarkus.elasticsearch.connection-timeout=30S
quarkus.elasticsearch.socket-timeout=300S

quarkus.package.jar.type=fast-jar
