/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Detailed banking information including IBAN, SWIFT, mandate details, etc.
 */
export interface BankDetailsDto {
  /**
   * Partner number - foreign key reference. Optional for new bank details (set automatically), required for updates.
   */
  partnerNumber?: number;
  /**
   * Sequential number matching the bank connection
   */
  sequenceNumber: number;
  /**
   * Bank key/identifier
   */
  bankKey?: string;
  /**
   * Country identifier code
   */
  countryId?: number;
  /**
   * Name of the account holder
   */
  accountHolder?: string;
  /**
   * Direct debit flag
   */
  directDebitFlag?: string;
  /**
   * Account block/lock flag
   */
  blockFlag?: boolean;
  /**
   * Street address
   */
  street?: string;
  /**
   * Postal code
   */
  postalCode?: string;
  /**
   * City name
   */
  city?: string;
  /**
   * SWIFT/BIC code
   */
  swiftCode?: string;
  /**
   * Last modification date
   */
  modificationDate?: string;
  /**
   * ID of person who made last modification
   */
  modifierId?: string;
  /**
   * Last stop period from
   */
  lastStopFrom?: string;
  /**
   * Last stop period to
   */
  lastStopTo?: string;
  /**
   * Reminder fee applicable flag
   */
  reminderFeeFlag?: string;
  /**
   * Payment arrears flag
   */
  arrearsFlag?: string;
  /**
   * International Bank Account Number
   */
  iban: string;
  /**
   * SEPA mandate reference in format ^EKF-[0-9]{7}-[0-9]{12}$
   */
  mandateReference?: string;
  /**
   * Date from which the SEPA mandate is valid
   */
  mandateValidFrom?: string;
  /**
   * Date when the SEPA mandate was signed
   */
  mandateSignatureDate?: string;
}

