/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of search criteria used for this group members search
 */
export interface GroupMembersSearchCriteriaSummary {
  /**
   * Group number searched for
   */
  groupNumber?: number;
}

