/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Partner summary information with advisor, sales area, and tracking details
 */
export interface PartnerSummaryDto {
  /**
   * Partner number (unique identifier)
   */
  partnerNumber: number;
  /**
   * Advisor/counselor assigned to the partner
   */
  advisor?: string;
  /**
   * User ID from sales area focus (Verkaufsgebietfokus)
   */
  vkfUserId?: string;
  /**
   * Sales area name (Gebietsname)
   */
  areaName?: string;
  /**
   * Branch designation/description
   */
  branchDesignation?: string;
  /**
   * User who created the partner record
   */
  creationUser?: string;
  /**
   * Timestamp when the partner record was created
   */
  creationTimestamp?: string;
  /**
   * First name of user who made the last change
   */
  lastChangeFirstName?: string;
  /**
   * Last name of user who made the last change
   */
  lastChangeLastName?: string;
  /**
   * Timestamp of the last change
   */
  lastChangeTimestamp?: string;
  /**
   * Full name of user who made the last change
   */
  lastChangeFullName?: string;
}

