/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Partner function information containing function definitions and descriptions
 */
export interface PartnerFunctionDto {
  /**
   * Unique partner function identifier - primary key
   */
  partnerFunctionId: number;
  /**
   * Function description/designation
   */
  functionDescription?: string;
  /**
   * Last modification date
   */
  modificationDate?: string;
}

