/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Postal code area focus information containing regional data and focus indicators
 */
export interface PostalCodeAreaFocusDto {
  /**
   * Postal code - primary key
   */
  postalCode: string;
  /**
   * Focus indicator
   */
  focus?: string;
  /**
   * Deletion flag (0 = active, others = deleted)
   */
  deletionFlag?: string;
  /**
   * Area number
   */
  areaNumber?: number;
  /**
   * Last modification date
   */
  lastModified?: string;
}

