/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContractDto } from '../model/models';
import { ContractSearchDto } from '../model/models';
import { ContractSearchResponse } from '../model/models';
import { CreateContractResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LoanGatewayServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create or retrieve contract with assets and vehicles (Gateway Proxy)
     * Creates a new contract with the provided details including asset data, or returns existing contract if one with the same client and code already exists. This endpoint implements idempotent behavior: calling it multiple times with the same client and code will return the same result. Certain fields associated with value ranges are validated before creation. Assets and vehicles are optional but if provided, each vehicle must have valid energy and category codes.
     * @param contractRequestDto
     */
    createContract(contractRequestDto: ContractDto, extraHttpRequestParams?: any): Observable<CreateContractResponseDto>;

    /**
     * Get contract by contract number (Gateway Proxy)
     * Retrieve a specific contract by its contract number with all related information. Proxied through gateway to loan service.
     * @param contractNumber Contract number to retrieve
     */
    findByContractNumber(contractNumber: string, extraHttpRequestParams?: any): Observable<ContractSearchDto>;

    /**
     * Comprehensive contract search (Gateway Proxy)
     * Search for contracts using comprehensive search criteria including contract number, application number, partner number, personal data (first name, name, date of birth), address information (postal code, city), and vehicle license plate. Supports both exact and partial matching. Use * for wildcard search in all text fields (contract number, application number, first name, name, postal code, city, vehicle license plate). Proxied through gateway to loan service.
     * @param client Client identifier for multi-tenant scenarios
     * @param contractNumber Contract number for exact match search. Use * for wildcard search
     * @param applicationNumber Application number
     * @param partnerNumber Partner number
     * @param firstName First name of contract holder (2-35 characters). Use * for wildcard search
     * @param name Last name of contract holder (2-35 characters). Use * for wildcard search
     * @param dateOfBirth Date of birth of contract holder
     * @param postalCode Postal code. Use * for wildcard search
     * @param city City name (2-35 characters). Use * for wildcard search
     * @param vehicleLicensePlate Vehicle license plate number. Use * for wildcard search
     */
    searchContracts(client: string, contractNumber?: string, applicationNumber?: number, partnerNumber?: number, firstName?: string, name?: string, dateOfBirth?: string, postalCode?: string, city?: string, vehicleLicensePlate?: string, extraHttpRequestParams?: any): Observable<ContractSearchResponse>;

}
