/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ContractRequestDto } from '../model/contract-request-dto';
// @ts-ignore
import { ContractSearchDto } from '../model/contract-search-dto';
// @ts-ignore
import { ContractSearchResponse } from '../model/contract-search-response';
// @ts-ignore
import { CreateContractResponseDto } from '../model/create-contract-response-dto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    LoanGatewayServiceInterface
} from './loan-gateway.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class LoanGatewayService extends BaseService implements LoanGatewayServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Create or retrieve contract with assets and vehicles (Gateway Proxy)
     * Creates a new contract with the provided details including asset data, or returns existing contract if one with the same client and code already exists. This endpoint implements idempotent behavior: calling it multiple times with the same client and code will return the same result. Certain fields associated with value ranges are validated before creation. Assets and vehicles are optional but if provided, each vehicle must have valid energy and category codes. 
     * @param contractRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createContract(contractRequestDto: ContractRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CreateContractResponseDto>;
    public createContract(contractRequestDto: ContractRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CreateContractResponseDto>>;
    public createContract(contractRequestDto: ContractRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CreateContractResponseDto>>;
    public createContract(contractRequestDto: ContractRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (contractRequestDto === null || contractRequestDto === undefined) {
            throw new Error('Required parameter contractRequestDto was null or undefined when calling createContract.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (oauth2) required
        localVarHeaders = this.configuration.addCredentialToHeaders('oauth2', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/loans/contract`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CreateContractResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: contractRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get contract by contract number (Gateway Proxy)
     * Retrieve a specific contract by its contract number with all related information. Proxied through gateway to loan service.
     * @param contractNumber Contract number to retrieve
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByContractNumber(contractNumber: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractSearchDto>;
    public findByContractNumber(contractNumber: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractSearchDto>>;
    public findByContractNumber(contractNumber: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractSearchDto>>;
    public findByContractNumber(contractNumber: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (contractNumber === null || contractNumber === undefined) {
            throw new Error('Required parameter contractNumber was null or undefined when calling findByContractNumber.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (oauth2) required
        localVarHeaders = this.configuration.addCredentialToHeaders('oauth2', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/loans/contract/${this.configuration.encodeParam({name: "contractNumber", value: contractNumber, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractSearchDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Comprehensive contract search (Gateway Proxy)
     * Search for contracts using comprehensive search criteria including contract number, application number, partner number, personal data (first name, name, date of birth), address information (postal code, city), and vehicle license plate. Supports both exact and partial matching. Use * for wildcard search in all text fields (contract number, application number, first name, name, postal code, city, vehicle license plate). Proxied through gateway to loan service.
     * @param client Client identifier for multi-tenant scenarios
     * @param contractNumber Contract number for exact match search. Use * for wildcard search
     * @param applicationNumber Application number
     * @param partnerNumber Partner number
     * @param firstName First name of contract holder (2-35 characters). Use * for wildcard search
     * @param name Last name of contract holder (2-35 characters). Use * for wildcard search
     * @param dateOfBirth Date of birth of contract holder
     * @param postalCode Postal code. Use * for wildcard search
     * @param city City name (2-35 characters). Use * for wildcard search
     * @param vehicleLicensePlate Vehicle license plate number. Use * for wildcard search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchContracts(client: string, contractNumber?: string, applicationNumber?: number, partnerNumber?: number, firstName?: string, name?: string, dateOfBirth?: string, postalCode?: string, city?: string, vehicleLicensePlate?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractSearchResponse>;
    public searchContracts(client: string, contractNumber?: string, applicationNumber?: number, partnerNumber?: number, firstName?: string, name?: string, dateOfBirth?: string, postalCode?: string, city?: string, vehicleLicensePlate?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractSearchResponse>>;
    public searchContracts(client: string, contractNumber?: string, applicationNumber?: number, partnerNumber?: number, firstName?: string, name?: string, dateOfBirth?: string, postalCode?: string, city?: string, vehicleLicensePlate?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractSearchResponse>>;
    public searchContracts(client: string, contractNumber?: string, applicationNumber?: number, partnerNumber?: number, firstName?: string, name?: string, dateOfBirth?: string, postalCode?: string, city?: string, vehicleLicensePlate?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (client === null || client === undefined) {
            throw new Error('Required parameter client was null or undefined when calling searchContracts.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>contractNumber, 'contractNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>applicationNumber, 'applicationNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>partnerNumber, 'partnerNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>firstName, 'firstName');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>name, 'name');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>dateOfBirth, 'dateOfBirth');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>postalCode, 'postalCode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>city, 'city');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>vehicleLicensePlate, 'vehicleLicensePlate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>client, 'client');

        let localVarHeaders = this.defaultHeaders;

        // authentication (oauth2) required
        localVarHeaders = this.configuration.addCredentialToHeaders('oauth2', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/loans/contract-search`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractSearchResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
