/**
 * traefik-microstack API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {PartnerEditDto} from '../model/models';

import {Configuration} from '../configuration';


export interface PartnerGatewayServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get partner by number with complete information (Gateway Proxy)
   * Retrieves complete partner information including all contact persons, addresses, and telecommunication details. Proxied through gateway to partner service.
   * @param partnerNumber Partner number to retrieve
   */
  findByPartnerNumber(partnerNumber: number, extraHttpRequestParams?: any): Observable<PartnerEditDto>;

  /**
   * Save partner data (Gateway Proxy)
   * Updates an existing partner. Proxied through gateway to partner service.
   * @param partnerNumber Partner number to update
   * @param partnerDto
   */
  savePartner(partnerNumber: number, partnerDto: PartnerEditDto, extraHttpRequestParams?: any): Observable<PartnerEditDto>;

}
