/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDto } from './vehicle-dto';


/**
 * Asset data
 */
export interface AssetDto { 
    /**
     * Asset number - business identifier
     */
    assetNumber?: number;
    /**
     * Asset start date
     */
    startDate?: string;
    /**
     * Asset end date
     */
    endDate?: string;
    /**
     * List of vehicles associated with this asset
     */
    vehicles?: Array<VehicleDto>;
}

