/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of search criteria used for contract search
 */
export interface ContractSearchCriteriaSummary { 
    /**
     * Contract number searched for
     */
    contractNumber?: string;
    /**
     * Application number searched for
     */
    applicationNumber?: number;
    /**
     * Partner number searched for
     */
    partnerNumber?: number;
    /**
     * First name searched for
     */
    firstName?: string;
    /**
     * Last name/company name searched for
     */
    name?: string;
    /**
     * Date of birth searched for
     */
    dateOfBirth?: string;
    /**
     * Postal code searched for
     */
    postalCode?: string;
    /**
     * City searched for
     */
    city?: string;
    /**
     * Vehicle license plate searched for
     */
    vehicleLicensePlate?: string;
}

