/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractSearchDto } from './contract-search-dto';
import { ContractSearchCriteriaSummary } from './contract-search-criteria-summary';


/**
 * Contract search response with results and metadata
 */
export interface ContractSearchResponse { 
    /**
     * List of contract search results
     */
    contracts: Array<ContractSearchDto>;
    /**
     * Total number of matching contracts
     */
    totalCount?: number;
    /**
     * Number of contracts returned in this response
     */
    returnedCount?: number;
    searchCriteria?: ContractSearchCriteriaSummary;
}

