/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractDto } from './contract-dto';


/**
 * Create contract response wrapper
 */
export interface CreateContractResponseDto { 
    contract?: ContractDto;
    /**
     * Status and informational messages
     */
    messages?: Array<string>;
}

