/**
 * traefik-microstack API Gateway
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Vehicle data
 */
export interface VehicleDto { 
    /**
     * Asset sequence number for this vehicle
     */
    assetSequenceNumber?: number;
    /**
     * Vehicle description
     */
    description?: string;
    /**
     * External reference identifier
     */
    extReference?: string;
    /**
     * Vehicle quantity
     */
    quantity?: number;
    /**
     * Initial amount/value of the vehicle
     */
    initialAmount?: number;
    /**
     * Vehicle design details
     */
    design?: string;
    /**
     * First registration date
     */
    firstRegistrationDate?: string;
    /**
     * Energy type code. Valid values: PETROL, DIESEL, ELECTRIC, HYBRID, PLUGIN, NATGAS, LIQGAS, HYDROGEN, SPECIAL
     */
    energy?: string;
    /**
     * Vehicle power in kW
     */
    power?: number;
    /**
     * Vehicle Identification Number
     */
    vin?: string;
    /**
     * License plate number
     */
    licensePlate?: string;
    /**
     * Manufacturer code (HSN)
     */
    manufacturer?: string;
    /**
     * Manufacturer type code (TSN)
     */
    manufacturerType?: string;
    /**
     * Vehicle brand
     */
    brand?: string;
    /**
     * Vehicle category code. Valid values: USED, NEW, YOUNG
     */
    category?: string;
    /**
     * Vehicle type/model
     */
    type?: string;
    /**
     * Cylinder capacity
     */
    cylinderCapacity?: string;
    /**
     * Body type/car type
     */
    bodyType?: string;
    /**
     * Whether this vehicle is collateral only
     */
    collateralOnly?: boolean;
    /**
     * Kind of driver information
     */
    kindOfDriver?: string;
    /**
     * Insurance company name
     */
    insuranceCompany?: string;
    /**
     * Insurance coverage type
     */
    coverageType?: string;
    /**
     * Insurance deductible amount
     */
    deductible?: string;
    /**
     * Schwacke code for vehicle valuation
     */
    schwackeCode?: string;
}

